services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - piscineds_network

  pgadmin:
    image: dpage/pgadmin4:9.8.0
    container_name: pgadmin
    env_file:
      - ../.env
    ports:
      - "4001:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ../../:/data
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - piscineds_network

volumes:
  postgres_data:
  pgadmin_data:
networks:
  piscineds_network:
    driver: bridge