services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../data/subject/subject:/data
      - ./scripts:/scripts
    restart: unless-stopped
    networks:
      - piscine_datascience_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: piscineds_pgadmin
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./conf/servers.json:/pgadmin4/servers.json:ro
      - ./conf/pgpass:/pgadmin4/pgpass:ro
      - ./scripts:/scripts:ro
    environment:
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - piscine_datascience_network

volumes:
  postgres_data:
  pgadmin_data:
    
networks:
  piscine_datascience_network:
    name: piscine_datascience_network
    driver: bridge
    external: false